layabox/LayaAir

src/layaAir/laya/renders/RenderSprite.ts

当`scrollRect.height=0`或者`scrollRect.width=0`时
https://github.com/layabox/LayaAir/blob/master/src/layaAir/laya/webgl/shader/d2/files/texture.vs.glsl#L58
中
```glsl
cliped=vec2( dot(clippos,clipMatDir.xy)/clipw/clipw, dot(clippos,clipMatDir.zw)/cliph/cliph);
```
其中`clipw`或者`cliph`会相应的为`0`，导致出现`除0`问题。
最终导致显示效果达不到预期
也可在此处进行判定，改为
```glsl
if(cliph>0.){
cliph = dot(clippos,clipMatDir.zw)/cliph/cliph;
}
if(clipw>0.){
clipw=dot(clippos,clipMatDir.xy)/clipw/clipw;
}
cliped=vec2( clipw, cliph);
```
不过这样会浪费一次`drawcall`，我认为直接改掉`RenderSprite`的`_clip`方法更省

修复当scrollRect.height或者scrollRect.width为0时的显示错误问题

---

src/layaAir/laya/media/h5audio/AudioSoundChannel.ts

当游戏切后台以后，时间如果过长，Chrome，FireFox，Safari浏览器会将音频卸载，并抛出`abort`事件  
此时，游戏切回前台时，并未判断channel状态，会导致调用`play`报错 DOMException: Failed to load because no supported source was found

修复当音频切后台时间过长，再恢复前台时会报错的问题

---

src/layaAir/laya/d3/component/Animator.ts

crossfade时会保存当前的pose数据，与非additive层动画帧数据做权重融合时不会有问题，但additive层这样处理会有问题。

Fix crossfade error when have additive layers

---

src/layaAir/laya/resource/Context.ts

1.问题描述
当图片的sizeGrid设置为上下左右全部需要拉伸时，但是实际设置图片的宽高只有一个方向需要拉伸，这时候会必现拉伸错乱的bug。
2.问题原因
在文件LayaAir/src/layaAir/laya/resource/Context.ts的函数drawTextureWithSizeGrid中，
在得到拉伸位置top，left， right， bottom后会设置拉伸比例:
```
var d_top = top / h;
var d_left = left / w;
var d_right = right / w;
var d_bottom = bottom / h;
```
但是这时如果设置的宽或高等于图片的原始宽或高时，会重置对应的位置，代码如下:
```
if (width == w) {
left = right = 0;
}
if (height == h) {
top = bottom = 0;
}
```
但是在重置之前已经设置了对应的d_top，d_left，d_right，d_bottom，现在把位置重置了又没有重置位置比例，导致问题出现。
3.问题解决
把位置比例初始化放到重置位置的代码之后:
```
if (width == w) {
left = right = 0;
}
if (height == h) {
top = bottom = 0;
}
var d_top = top / h;
var d_left = left / w;
var d_right = right / w;
var d_bottom = bottom / h;
```

fix九宫格渲染bug

---

src/layaAir/laya/d3/component/Animator.ts
src/layaAir/laya/d3/core/render/BaseRender.ts
src/layaAir/laya/d3/core/scene/Scene3D.ts
src/layaAir/laya/d3/graphics/FrustumCulling.ts

BaseRender中的_visible可见性标识是在Camera做FrustumCulling的时候设置的，如果有两个Camera渲染不同的Layer，被渲染的物体属于第一个Camera的层，那么_visible标识会在第二个Camera渲染时被置为false。
这导致Animator根据_visible来更新是错误的。这里增加_anyCameraVisible标识来表示该物体在一帧中是否可见的状态。

修复BaseRender可见性标识不正确导致Animator更新不正确的问题

---

src/layaAir/laya/d3/component/SimpleSingletonList.ts
src/layaAir/laya/d3/physics/PhysicsComponent.ts

PhysicsComponent._onDisable处理this._simulation._physicsUpdateList.remove(this)的条件之一是this._enabled为true，而_onDisable被调用之前Component.set enabled已经将this._enable置为false。
这导致了下面情况的崩溃：
1、enable状态下修改transform，PhysicsComponent._onTransformChanged将自己加入_physicsUpdateList
2、disable，这里_onDisable无法将自己从_physicsUpdateList中移除
3、destroy，销毁对象
4、下一帧物理更新_derivePhysicsTransformation崩溃

修复PhysicsComponent enable状态处理不正确导致崩溃

---

src/layaAir/laya/display/Node.ts

Node层级激活，遍历子节点存在条件漏判情况
当一个节点激活的时候，也就是执行 `_activeHierarchy` 方法，会遍历调用子节点的 `_activeHierarchy` 方法，调用的时候只检查了字节点的 `ACTIVE` 状态，没有检查 `READY` 状态，可能会遇到激活子节点的时候其仍未加载完成的情况，这样子节点的 `onAwake` 会提前执行。
现在有一个场景（Scene） `mainScene`，场景上挂载了控制器（Script） `mainController`，然后在 `mainController` 的 `onAwake` 中实例化另一个 View，然后挂载到场景中
``` ts
// mainController
public onAwake() {
const menu = new MenuView();
this.owner.addChild(menu);
}
```
因为 `mainController` 脚本的激活是在 `mainScene` 遍历层级激活之前，所以这时候 MenuView 的实例已经被挂载到 `mainScene` 上了，但是它自己仍在异步加载中。
由于层级激活判断条件缺少 `READY` 判断，所以 `mainScene` 层级激活时也会调用 MenuView 实例的 `_activeHierarchy`，最终导致它的 `onAwake` 提前被调用，里面拿到的组件引用也就是都 `undefined`

fix: Node节点激活bug

---

src/layaAir/Laya3D.ts
src/layaAir/laya/d3/core/SimpleSkinnedMeshRenderer.ts
src/layaAir/laya/d3/core/SimpleSkinnedMeshSprite3D.ts
src/layaAir/laya/d3/core/SkinnedMeshRenderer.ts
src/layaAir/laya/d3/core/SkinnedMeshSprite3DShaderDeclaration.ts
src/layaAir/laya/d3/graphics/SubMeshInstanceBatch.ts
src/layaAir/laya/d3/resource/models/Mesh.ts
src/layaAir/laya/d3/shader/Shader3D.ts
src/layaAir/laya/d3/shader/ShaderInit3D.ts
src/layaAir/laya/d3/shader/ShaderPass.ts
src/layaAir/laya/d3/shader/files/Mesh-BlinnPhong.vs
src/layaAir/laya/d3/utils/Scene3DUtils.ts

1、Modify some properties in skinnedmeshrender to inheritable data
2、Add simplebone macro, add U_ SimpleAnimatorTexture,u_ SimpleAnimatorParams,u_ SimpleAnimatorTextureSize
3、Add instancebuffer and instancesimpleanimatordata data of simpleanimator, and add functions for creating instancebuffer
4、Creating instancebuffer in mesh class
5、The method of dynamically modifying macro attributes in shader3d
6、Add the uniform attribute of simpleanimator in blinnphoneholder
7、Add a function to replace attribute dynamically in shaderpass
8、Mesh- BlinnPhong.vs Add skin code of simpleanimator in
9、Add the node of simpleskinnedmeshsprite

SimpleAnimator

---

src/layaAir/Laya3D.ts
src/layaAir/laya/d3/core/Bounds.ts
src/layaAir/laya/d3/core/MeshRenderer.ts
src/layaAir/laya/d3/core/MeshSprite3D.ts
src/layaAir/laya/d3/core/MeshSprite3DShaderDeclaration.ts
src/layaAir/laya/d3/core/RenderableSprite3D.ts
src/layaAir/laya/d3/core/SkinnedMeshRenderer.ts
src/layaAir/laya/d3/core/material/PBRSpecularMaterial.ts
src/layaAir/laya/d3/core/material/PBRStandardMaterial.ts
src/layaAir/laya/d3/core/reflectionProbe/ReflectionProbe.ts
src/layaAir/laya/d3/core/reflectionProbe/ReflectionProbeManager.ts
src/layaAir/laya/d3/core/render/BaseRender.ts
src/layaAir/laya/d3/core/render/SubMeshRenderElement.ts
src/layaAir/laya/d3/core/scene/Scene3D.ts
src/layaAir/laya/d3/shader/ShaderInit3D.ts
src/layaAir/laya/d3/shader/files/GlobalIllumination.glsl
src/layaAir/laya/d3/shader/files/PBRLibs/PBRCore.glsl
src/layaAir/laya/d3/utils/Scene3DUtils.ts

2、修复Bounds类中计算包围盒相交体积的方法
3、MeshRender中增加反射探针的更新
4、MeshSprite3D.ts中增加SPECCUBE_BOX_PROJECTION宏
5、RenderableSprite3D.ts中增加反射探针的uniform
6、SkinnedMeshRenderer.ts中增加反射探针更新
7、u_ReflectCubeHDRParams，u_ReflectTexture中调整为逐精灵传输增加反射探针的uniform
8、ReflectionProb中增加size offseet属性 增加反射探针解析
9、完善反射探针管理类
10、增加反射探针模式 off  simple
11、不是Scene的反射探针不可进行instance合并
12、Scene3D中增加反射探针更新
13、GlobalIllumination.glsl中增加反射探针uniform  增加反射采样方向的偏移函数

1、增加ReflectionProbe节点加载

---

src/layaAir/laya/d3/core/render/command/BlitScreenQuadCMD.ts
src/layaAir/laya/d3/core/render/command/CommandBuffer.ts

1、CommandBuffer_BlurryGlass示例 修复场景窗口变化后，效果不对的bug
2、CommandBuffer.ts增加setGlobalData的各个函数
3、增加Blit命令的Material接口blitScreenQuadByMaterial
4、删除多余代码
1、CommandBuffer_ The blurryglass example fixes the bug that the effect is not correct after the scene window changes
2、 CommandBuffer.ts Add setglobaldata functions
3. Add the material interface of BLIT command blitscreenqudbymaterial
4. Delete redundant code

add globalDataCMD

---

src/layaAir/laya/physics/Physics.ts
src/layaAir/laya/physics/RigidBody.ts

updatePhysicsByWorldRoot 手动更新物理世界(worldRoot); 更新物理世界后，当 RigidBody.allowSleep=false时，还需调整point位置

updatePhysicsByWorldRoot 手动更新物理世界(worldRoot)

---

src/layaAir/laya/d3/component/Animator.ts
src/layaAir/laya/d3/core/particleShuriKen/ShurikenParticleRenderer.ts
src/layaAir/laya/d3/graphics/IndexBuffer3D.ts
src/layaAir/laya/d3/graphics/VertexBuffer3D.ts
src/layaAir/laya/d3/physics/PhysicsSimulation.ts
src/layaAir/laya/html/dom/HTMLDivElement.ts
src/layaAir/laya/net/Loader.ts
src/layaAir/laya/net/TTFLoader.ts
src/layaAir/laya/webgl/text/TextRender.ts

1、修复物理形状包围盒的检测第二次输出信息错误的bug
2、修复粒子包围盒重力影响的bug
3、修复粒子CPUGPU统计不准确的bug
4、修复动画事件调用播放动画函数导致事件错乱的bug
5、HTMLDivElement 宽高设置不正确
6、2D图集加载pvr出错的bug（loader）
7、TTFLoader  兼容ttf后缀（TTFLoader）

修复物理形状包围盒的检测第二次输出信息错误的bug

---

src/layaAir/laya/device/media/HtmlVideo.ts

默认放开webGL对纹理数据的跨域限制

---

src/layaAir/laya/d3/core/Camera.ts
src/layaAir/laya/d3/depthMap/DepthPass.ts
src/layaAir/laya/d3/resource/MulSampleRenderTexture.ts
src/layaAir/laya/d3/resource/RenderTexture.ts
src/layaAir/laya/d3/shader/files/Lighting.glsl
src/layaAir/laya/d3/shader/files/ShadowCasterVS.glsl

DepthPass
修改深度Pass，兼容深度图和阴影图获取深度的方式差异
Camera
重构Camera渲染标记
增加渲染优化参数canBlitDepth，主流程的渲染深度图可以直接作用于后期处理
增加设置Camera的深度贴图格式，增加深度图32位以及模板图
解决iOS中使用CopyTexSubImage2D特别慢的bug

重构Rendertexture

---

src/layaAir/laya/d3/physics/Rigidbody3D.ts

before
`if (data.gravity) {
this.gravity.fromArray(data.gravity);
this.gravity = this.gravity;
}`
after
`if (data.gravity) {
var gravity = this.gravity;
gravity.fromArray(data.gravity);
this.gravity = gravity;
}`

fix parse data with 'gravity' property doesn't work

---

src/layaAir/laya/ui/Dialog.ts
src/layaAir/laya/ui/DialogManager.ts

实际项目中遇到的问题。
**一句话描述：**
dialog.destroy() 之后，会遗留遮罩层。
**稍微复杂的逻辑：**
调用 dialog.close() 之后，在 dialog.closeEffect 中的 **tween 执行完毕前如果 dialog 被 destroy 了**，那么就不会执行到 DialogManager 中的 doClose（即 Tween 的 complete 不会被执行）。此时 doClose 中用于更新 maskLayer 的 _checkMask 方法也就没有机会执行，结果就是弹窗关闭了，但是遮罩层还在。
**dialog.close() 的 tween 执行完毕前调用 dialog.destroy() 这个场景是普遍存在的**
比如当前场景 (Scene.autoDestroyAtClosed = true) 中打开的 Dialog 弹窗上点击退出游戏副本，
此时的逻辑通常是关闭 Dialog 弹窗，并跳转到新的场景 ( Scene.open("......", true) ) 并自动关闭当前场景，
在 scene.onDestroy() 中清理内存时会调用 dialog.destroy()，此时就会触发上述逻辑。

fix: Update the maskLayer index, or remove it after Dialog destroyed.

---

src/layaAir/laya/display/Text.ts

修改Text.ts中的行排版,让文字不与图片进行居中对齐,否则超链接加图文混排会出现意料之外的显示结果
修复相关问题 #1334

修改Text.ts中的排版

---

src/layaAir/laya/spine/Spine2DRenderNode.ts

Set the node.source And then destroy errors caused by node before loading is complete.（健壮性）

fix:spine bug

---

src/layaAir/laya/d3/core/particleShuriKen/module/FrameOverTime.ts
src/layaAir/laya/spine/Spine2DRenderNode.ts
src/layaAir/laya/spine/SpineTemplet.ts
src/layaAir/laya/spine/optimize/SpineOptimizeRender.ts

1.Data residue resulting from switching from the RandomTwoConstant type to other types causes errors during cloning.(RandomTwoConstant类型换到别的类型产生的数据残留，导致clone时报错)
2.Reusing RenderElement and setting its geometry causes rendering state errors in subsequent uses.(重复使用的 RenderElement 设置 geo 导致下一次使用渲染状态错误)
3.Planning to add spine width and height functionality.(准备增加spine宽高功能)

fix : Spine And ShurikenParticle.clone BUG

---

src/layaAir/jsLibs/spine-core-4.2.js

4.2的spine尾部缺失 window.spine = spine; 导致小游戏环境中无法使用spine

Laya air 3.3 spine4.2小游戏中的全局修复
