layabox/LayaAir

src/layaAir/laya/d3/math/Matrix4x4.ts

fix  matrix  bug

---

src/layaAir/laya/d3/core/scene/Scene3D.ts
src/layaAir/laya/d3/shader/ShaderInit3D.ts
src/layaAir/laya/d3/shader/files/PBRLibs/PBRSpecularLighting.glsl
src/layaAir/laya/d3/shader/files/PBRLibs/PBRStandardLighting.glsl
src/layaAir/laya/d3/shader/files/PBRLibs/PBRUtils.glsl
src/layaAir/laya/d3/shader/files/PBRSpecular.fs
src/layaAir/laya/d3/shader/files/PBRStandard.fs

Increasing PBR Multi-light Source Function

Increasing PBR Multi-light Source Function

---

src/samples/3d/LayaAir3D_Shader/Shader_GlowingEdge.ts
src/samples/3d/LayaAir3D_Shader/customShader/glowingEdgeShader.fs

The edge lighting example adapts to multiple light source variation bug fixes (which will occur under platforms that do not support multiple light sources)

Fix the edge lighting example bug

---

src/layaAir/Laya.ts
src/layaAir/Laya3D.ts
src/layaAir/laya/d3/animation/KeyframeNode.ts
src/layaAir/laya/d3/animation/KeyframeNodeList.ts
src/layaAir/laya/d3/core/FloatKeyframe.ts
src/layaAir/laya/d3/core/QuaternionKeyframe.ts
src/layaAir/laya/d3/core/Vector3Keyframe.ts
src/layaAir/laya/d3/shader/ShaderData.ts
src/layaAir/laya/device/media/Video.ts
src/layaAir/laya/renders/Render.ts
src/samples/3d/LayaAir3DTest_Native/SceneLoad3.ts
src/samples/3d/LayaAir3DTest_Native/SceneLoad4.ts

native code sync

---

src/publishTool/emiter.js
src/publishTool/index.js
src/publishTool/outConfig.json

1. outConfig.json -> add 'HTMLCanvasElement' :*
2. Type | null | undefined type processing

update tstoas tool

---

src/layaAir/laya/html/dom/HTMLBrElement.ts
src/layaAir/laya/html/dom/HTMLDivElement.ts
src/layaAir/laya/html/dom/HTMLDivParser.ts
src/layaAir/laya/html/dom/HTMLDocument.ts
src/layaAir/laya/html/dom/HTMLElement.ts
src/layaAir/laya/html/dom/HTMLHitRect.ts
src/layaAir/laya/html/dom/HTMLIframeElement.ts
src/layaAir/laya/html/dom/HTMLImageElement.ts
src/layaAir/laya/html/dom/HTMLLinkElement.ts
src/layaAir/laya/html/dom/HTMLStyleElement.ts
src/layaAir/laya/html/utils/HTMLExtendStyle.ts
src/layaAir/laya/html/utils/HTMLParse.ts
src/layaAir/laya/html/utils/HTMLStyle.ts
src/layaAir/laya/html/utils/Layout.ts
src/layaAir/laya/html/utils/LayoutLine.ts

support：laya.html.js->  "Laya." Class

Synchronized bug modification

---

src/layaAir/laya/utils/Tween.ts

Reset Tween repeat state while clear

Fix Tween bug

---

.vscode/launch.json
gulpfile.js
src/publishTool/index.js

1.Modify to compile with local tsc.
2.F5 launch-> run gulp LayaAirBuild

UPDATE: About run gulpfile

---

src/layaAir/laya/utils/Browser.ts

修复更新ios13.1.1+版本后iPad设备的UA信息的识别=>
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko)"
参考资料：https://stackoverflow.com/questions/58019463

fix detect iPad device on IOS 13.1.1+

---

bin/laya.physics3D.runtime.js
src/layaAir/jsLibs/laya.physics3D.runtime.js

native physics

---

src/layaAir/laya/physics/RigidBody.ts
src/layaAir/laya/ui/TextArea.ts

Release 2.3.0

---

src/layaAir/laya/d3/core/material/PBRMaterial.ts
src/layaAir/laya/d3/core/scene/Scene3D.ts
src/layaAir/laya/d3/graphics/SphericalHarmonicsL2.ts
src/layaAir/laya/d3/shader/ShaderInit3D.ts
src/layaAir/laya/d3/shader/files/GlobalIllumination.glsl
src/layaAir/laya/d3/shader/files/Lighting.glsl
src/layaAir/laya/d3/shader/files/PBR.fs
src/layaAir/laya/d3/shader/files/PBRLibs/PBRCore.glsl
src/layaAir/laya/d3/shader/files/PBRLibs/PBRInput.glsl

change struct of PBRShader

---

src/layaAir/Laya.ts
src/publishTool/emiter.js
src/publishTool/index.js

Support :GetAccessor & SetAccessor

---

src/layaAir/laya/d3/physics/CharacterController.ts

_addToSimulation/_removeFromSimulation最终会调用到bullet btDiscreteDynamicsWorld::addAction/removeAction，Laya里有情形会将CCT add之后在没有remove的情况下_constructCharacter（如set stepHeight），这会导致bullet层的CCT没有remove却destory掉了，造成bullet崩溃在btDiscreteDynamicsWorld::updateActions时。

Fix CCT's crash in bullet

---

bin/index.js
src/layaAir/laya/d3/animation/KeyframeNode.ts
src/layaAir/laya/d3/animation/KeyframeNodeList.ts
src/layaAir/laya/d3/core/FloatKeyframe.ts
src/layaAir/laya/d3/core/QuaternionKeyframe.ts
src/layaAir/laya/d3/core/Vector3Keyframe.ts
src/layaAir/laya/renders/Render.ts

close webglplus

---

src/layaAir/laya/d3/animation/KeyframeNode.ts
src/layaAir/laya/d3/animation/KeyframeNodeList.ts
src/layaAir/laya/d3/core/FloatKeyframe.ts
src/layaAir/laya/d3/core/QuaternionKeyframe.ts
src/layaAir/laya/d3/core/Vector3Keyframe.ts
src/layaAir/laya/renders/Render.ts

Release 2.4.0

---

bin/index.js
src/layaAir/laya/d3/animation/KeyframeNode.ts
src/layaAir/laya/d3/animation/KeyframeNodeList.ts
src/layaAir/laya/d3/core/FloatKeyframe.ts
src/layaAir/laya/d3/core/QuaternionKeyframe.ts
src/layaAir/laya/d3/core/Vector3Keyframe.ts
src/layaAir/laya/renders/Render.ts

Release 2.5.0

---

src/layaAir/laya/d3/physics/PhysicsSimulation.ts
src/layaAir/laya/d3/physics/constraints/ConfigurableJoint.ts
src/layaAir/laya/d3/physics/constraints/ConstraintComponent.ts
src/layaAir/laya/d3/physics/constraints/FixedConstraint.ts

2、change joint and physics3D bullet

1、fix the question that Joints owner no Script error

---

src/layaAir/laya/d3/physics/PhysicsComponent.ts
src/layaAir/laya/d3/physics/constraints/ConfigurableJoint.ts
src/layaAir/laya/d3/physics/constraints/ConstraintComponent.ts
src/layaAir/laya/d3/physics/constraints/FixedConstraint.ts

add create joint function in onEnable
Adjust load joint

add constraintComponent parse

---

src/layaAir/laya/d3/physics/constraints/ConfigurableJoint.ts
src/layaAir/laya/d3/physics/constraints/ConstraintComponent.ts

change one function name

---

src/layaAir/laya/d3/physics/constraints/ConfigurableJoint.ts
src/samples/3d/LayaAir3D_Physics3D/PhysicsWorld_Generic6DofSpringConstraint.ts

Add a representation to configuartionJoint

Modify circular reference

---

bin/cannon.js
src/layaAir/laya/d3/core/scene/Scene3D.ts
src/layaAir/laya/d3/physicsCannon/CannonPhysicsSimulation.ts
src/layaAir/laya/d3/physicsCannon/CannonRigidbody3D.ts
src/layaAir/laya/d3/physicsCannon/shape/CannonCompoundColliderShape.ts
src/samples/3d/LayaAir3D_CannonjsTest/CannonPhysicsWorld_BaseCollider.ts
src/samples/3d/LayaAir3D_CannonjsTest/CannonPhysicsWorld_ColliderEvent.ts
src/samples/3d/LayaAir3D_CannonjsTest/CannonPhysicsWorld_PhysicsProperty.ts
src/samples/3d/LayaAir3D_CannonjsTest/CannonPhysicsWorld_RayCheck.ts

Modify trigger bug
Modify the bug of adding impulse
Modify the bug of ray collision point error

add cannonPhysics Example

---

src/layaAir/Config3D.ts
src/layaAir/laya/d3/core/light/LightQueue.ts
src/layaAir/laya/d3/core/scene/Scene3D.ts
src/layaAir/laya/d3/shader/files/Shadow.glsl

2、Spot light queues are sorted by light intensity to ensure correct shadows

1、Spotlight soft shadow macro shader not processed

---

src/layaAir/laya/d3/physics/PhysicsComponent.ts
src/layaAir/laya/d3/physics/constraints/ConfigurableJoint.ts
src/layaAir/laya/d3/physics/constraints/FixedConstraint.ts

Adjust the configjoint structure to be consistent with fixedjoint

Delete redundant structure code

---

src/layaAir/Laya3D.ts
src/layaAir/laya/d3/physics/constraints/ConfigurableConstraint.ts
src/layaAir/laya/net/LoaderManager.ts
src/layaAir/laya/utils/Utils.ts
src/samples/3d/LayaAir3D_Physics3D/PhysicsWorld_ConfigurableJoint.ts

Add compatibility to each platform (suffix does not support issues)

Uniform constraint name

---

src/layaAir/Laya3D.ts
src/layaAir/laya/net/Loader.ts

Load an LS file, and the process function calls back to 0-1
Ls file, process function callback value 0-1
Mutual influence, disordered callback progress
Solution, load LS file callback value 0-0.33; load LS file callback 0.33-1

Problem Description:

---

src/layaAir/laya/device/geolocation/Geolocation.ts
src/layaAir/laya/utils/Browser.ts
src/publishTool/emiter.js
src/publishTool/index.js
tslibs/nts/cannon.d.ts
tslibs/ts/cannon.d.ts

2.Partial code type specification
3.Removed Browser dependency of device

1.Publish tool updates

---

src/layaAir/laya/d3/core/material/PBRSpecularMaterial.ts
src/layaAir/laya/d3/core/material/PBRStandardMaterial.ts
src/layaAir/laya/d3/shader/Shader3D.ts
src/layaAir/laya/d3/shader/ShaderInit3D.ts
src/layaAir/laya/d3/shader/files/Effect.vs
src/layaAir/laya/d3/shader/files/Lighting.glsl
src/layaAir/laya/d3/shader/files/Mesh-BlinnPhong.vs
src/layaAir/laya/d3/shader/files/PBRLibs/PBRVertex.glsl
src/layaAir/laya/d3/shader/files/ShadowCasterVS.glsl
src/layaAir/laya/d3/shader/files/Unlit.vs
src/samples/3d/LayaAir3D_Animation3D/SimpleSkinMeshSprite3D.ts

add simpleAnimator Change all shader
change bug of spot lightMap for pbrMaterial
add a samples  /3d/LayaAir3D_Animation3D/SimpleSkinMeshSprite3D.ts

add a samples  /3d/LayaAir3D_Animation3D/SimpleSkinMeshSprite3D.ts

---

src/layaAir/laya/d3/core/scene/Scene3D.ts

repair Scene3D/s ReflectionTextureCube reference manage bug

repair Scene3D/s ReflectionTextureCube reference manage bug

---

src/layaAir/laya/d3/core/material/PBRSpecularMaterial.ts
src/layaAir/laya/d3/core/material/PBRStandardMaterial.ts
src/layaAir/laya/d3/shader/files/Lighting.glsl
src/layaAir/laya/d3/shader/files/Mesh-BlinnPhong.vs
src/layaAir/laya/d3/shader/files/PBRLibs/PBRVSInput.glsl
src/layaAir/laya/d3/shader/files/Unlit.vs

reqair pbr Material cant instance bug
reqair SimpleAnimator shader bug

 Restructuring

---

src/layaAir/laya/d3/core/light/LightSprite.ts
src/layaAir/laya/d3/core/light/ShadowUtils.ts
src/layaAir/laya/d3/shader/files/Lighting.glsl

Fixed a bug in spotlight shadows affected by scale
Fix the lighting error of spotlight

fixed some bug

---

src/layaAir/laya/d3/core/Bounds.ts
src/layaAir/laya/d3/core/material/PBRSpecularMaterial.ts
src/layaAir/laya/d3/core/material/PBRStandardMaterial.ts
src/layaAir/laya/d3/core/reflectionProbe/ReflectionProbe.ts
src/layaAir/laya/d3/core/reflectionProbe/ReflectionProbeList.ts
src/layaAir/laya/d3/core/reflectionProbe/ReflectionProbeManager.ts
src/layaAir/laya/d3/core/render/BaseRender.ts
src/layaAir/laya/d3/core/scene/Scene3D.ts
src/layaAir/laya/d3/shader/Shader3D.ts
src/layaAir/laya/d3/shader/ShaderInit3D.ts

2、增加shader是否支持反射的接口
3、baseRender中添加物体是否支持反射的判断以及方法
4、Scene3D中增加反射探针管理类
5、各个材质修改支持反射探针属性
add：
增加反射探针类
增加反射探针队列类
增加反射探针管理类

1、添加Bounds相交体积计算

---

src/layaAir/laya/d3/component/Animator.ts
src/layaAir/laya/d3/component/PostProcess.ts
src/layaAir/laya/resource/Texture.ts

后期处理减少一次赋值RenderTarget
Texture增加RenderTexture转换

Animator.ts恢复动画播放速度

---

src/layaAir/laya/d3/core/SimpleSkinnedMeshRenderer.ts
src/layaAir/laya/d3/core/SimpleSkinnedMeshSprite3D.ts
src/layaAir/laya/d3/core/render/BaseRender.ts
src/layaAir/laya/resource/BaseTexture.ts
src/layaAir/laya/resource/Texture2D.ts
src/layaAir/laya/resource/TextureFormat.ts
src/layaAir/laya/webgl/SystemUtils.ts

增加R16G16B16A16的TextureFormat
修改SimpleSKinnedMeshTexture的读取，增加压缩模式
修复原先R16G16B16A16的bug
增加半浮点数纹理支持判断

修改boneNum的判断地方，合并同一动画节点下面的多个SimpleSkinnedMeshsprite3D

---

src/layaAir/laya/d3/component/PostProcess.ts
src/layaAir/laya/d3/core/Camera.ts
src/layaAir/laya/d3/core/render/BaseRender.ts
src/layaAir/laya/d3/core/render/command/CommandBuffer.ts
src/layaAir/laya/d3/core/render/command/SetShaderDataCMD.ts
src/layaAir/laya/d3/core/scene/Scene3D.ts
src/layaAir/laya/d3/shader/ShaderInstance.ts
src/samples/3d/LayaAir3D_PostProcess/PostProcess_Blur.ts

* 修改后期处理的调用流程  修复postProcess不断添加会不断变卡的流程
修改后期处理在Camera中的调用 删除后期CommondBuffer数据集合
修改ShaderDataCMDType枚举名字为ShaderDataType
增加Scene动态Uniform的变量的增加  大大的增加了开发者的易用性
修改blur示例

修改后期处理流程，增加shaderDataCMDType枚举，动态增加Scene Uniform，修改blur示例

---

src/layaAir/laya/d3/core/render/command/ClearRenderTextureCMD.ts
src/layaAir/laya/d3/core/render/command/CommandBuffer.ts

增加clearRenderTarget命令缓存（Increase clearrendertarget command cache）

增加clearRenderTarget命令缓存

---

src/layaAir/laya/d3/shader/ShaderInit3D.ts
src/layaAir/laya/d3/shader/files/Effect.vs
src/layaAir/laya/d3/shader/files/LayaUtile.glsl
src/layaAir/laya/d3/shader/files/Mesh-BlinnPhong.vs
src/layaAir/laya/d3/shader/files/PBR.vs
src/layaAir/laya/d3/shader/files/PBRLibs/PBRVSInput.glsl
src/layaAir/laya/d3/shader/files/Unlit.vs
src/layaAir/laya/resource/VideoTexture.ts
src/samples/3d/LayaAir3D_Resource/LoadResourceDemo.ts
src/samples/view/IndexView3D.ts

增加LayaUtile.glsl

---

src/extensions/debug/DebugPanel.ts

debugpanel问题修复：

---

src/layaAir/laya/d3/core/scene/Scene3D.ts
src/layaAir/laya/d3/resource/TextureCube.ts

修复textureCube加载分析

---

src/layaAir/laya/d3/shader/files/Mesh-BlinnPhong.fs
src/layaAir/laya/d3/shader/files/PBRLibs/PBRVertex.glsl
src/layaAir/laya/webgl/WebGLContext.ts

1、修复blinnPhongMaterial的DirctLightMap的bug
2、修复高差算法的bug
3、将图片限制增加至设备支持最大图片

修复blinnPhongMaterial的DirctLightMap的bug

---

src/layaAir/laya/d3/core/particleShuriKen/ShurikenParticleSystem.ts
src/layaAir/laya/d3/core/particleShuriKen/module/VelocityOverLifetime.ts
src/layaAir/laya/d3/core/reflectionProbe/ReflectionProbeManager.ts
src/layaAir/laya/d3/physics/Rigidbody3D.ts
src/layaAir/laya/d3/physics/constraints/ConfigurableConstraint.ts
src/layaAir/laya/d3/physics/constraints/ConstraintComponent.ts
src/layaAir/laya/d3/physicsCannon/CannonRigidbody3D.ts
src/layaAir/laya/d3/resource/TextureCube.ts
src/layaAir/laya/d3/shader/DefineDatas.ts
src/layaAir/laya/d3/shader/files/PBRLibs/PBRVertex.glsl

2、修复物理获取Gravity的bug
3、优化修复宏定义增加移除代码
4、修复物理关节删除的bug
5、修复textureCube加载bug
6、修复PBR中高差贴图算法的bug
7、修复粒子clone中的bug
8、修复cannon刚体旋转速度设置的bug
9、修改粒子闪烁的bug

1、修复设置Scene3D中的reflect不生效的bug

---

src/layaAir/laya/d3/graphics/SubMeshStaticBatch.ts
src/layaAir/laya/particle/shader/Particle.ps.glsl

1、删除小米编译会出错的中文注释
2、修复静态合并切线算法错误

修复静态合并切线算法错误

---

src/layaAir/laya/d3/core/pixelLine/PixelLineSprite3D.ts
src/layaAir/laya/d3/core/render/BaseRender.ts
src/layaAir/laya/d3/graphics/SubMeshStaticBatch.ts

优化PixelLineSprite3D  没有线的时候不加入渲染

---

src/layaAir/laya/d3/core/SimpleSkinnedMeshRenderer.ts
src/layaAir/laya/d3/core/material/PBRSpecularMaterial.ts
src/layaAir/laya/d3/core/material/PBRStandardMaterial.ts
src/layaAir/laya/d3/core/render/SubMeshRenderElement.ts
src/layaAir/laya/d3/graphics/SubMeshInstanceBatch.ts
src/layaAir/laya/d3/graphics/Vertex/VertexMesh.ts
src/layaAir/laya/d3/resource/models/Mesh.ts
src/layaAir/laya/d3/resource/models/SubMesh.ts
src/layaAir/laya/d3/shader/Shader3D.ts
src/layaAir/laya/d3/shader/ShaderPass.ts

2、最大Instance合并数目改为静态
3、去掉InstanceMVP数据
4、增加自定义顶点格式
5、去掉动态替换Attribute的不合理代码

1、去掉InstanceMVPMatrix的渲染更新

---

src/layaAir/laya/d3/core/render/command/DrawMeshInstancedCMD.ts
src/layaAir/laya/d3/core/render/command/MaterialInstanceProperty.ts
src/layaAir/laya/d3/core/render/command/MaterialInstancePropertyBlock.ts
src/layaAir/laya/d3/math/Vector2.ts
src/layaAir/laya/d3/math/Vector3.ts
src/layaAir/laya/d3/math/Vector4.ts

增加MaterialInstanceProperty功能
增加MaterialInstancePropertyBlock功能
Vector2 Vector3 Vector4 增加toArray方法

增加drawMeshInstance功能

---

src/layaAir/laya/d3/core/render/command/CommandBuffer.ts
src/layaAir/laya/d3/physicsCannon/CannonPhysicsComponent.ts

修复cannonBug

---

src/layaAir/Config.ts
src/layaAir/laya/d3/resource/RenderTexture.ts

设置DepthTexture采样为点采样 线性采样webgl2.0的深度贴图会变黑

打开Webgl2.0的设置

---

src/layaAir/laya/d3/resource/RenderTexture.ts

1\提交Webgl2.0MulSamplerRenderbuffer

---

src/layaAir/Laya3D.ts
src/layaAir/laya/resource/Texture2D.ts
src/layaAir/laya/resource/TextureFormat.ts

提交健壮pvr ktx加载

---

src/extensions/performanceTool/PerformanceDataTool.ts
src/layaAir/laya/resource/BaseTexture.ts
src/layaAir/laya/resource/Texture2D.ts
src/layaAir/laya/resource/TextureFormat.ts
src/samples/3d/LayaAir3D_Texture/GPUCompression_ASTC.ts
src/samples/3d/LayaAir3D_Texture/GPUCompression_ETC2.ts

增加ETCRGB_Alpha8 ASTC剩余图片格式
增加测试案例ASTC  ETC

性能分析工具 修复为step为1报错的bug

---

src/layaAir/laya/d3/core/render/BaseRender.ts
src/layaAir/laya/d3/core/scene/BoundsOctree.ts
src/layaAir/laya/d3/core/scene/BoundsOctreeNode.ts
src/layaAir/laya/d3/core/scene/IOctreeObject.ts
src/layaAir/laya/d3/core/scene/Scene3D.ts
src/layaAir/laya/d3/core/scene/SceneRenderManager/IRenderNodeObject.ts
src/layaAir/laya/d3/core/scene/SceneRenderManager/ISceneRenderManager.ts
src/layaAir/laya/d3/graphics/FrustumCulling.ts

新增规范接口ＩＳｃｅｎｅＲｅｎｄｅｒＭａｎａｇｅｒ
修改八叉树符合规范，用于以后扩展场景节点管理

增加架构替换渲染节点管理

---

src/layaAir/laya/resource/BaseTexture.ts
src/layaAir/laya/resource/WrapMode.ts
src/samples/3d/LayaAir3D_Advance/CommandBufferDemo/GlassShader.fs
src/samples/3d/LayaAir3D_Advance/CommandBufferDemo/GlassShader.vs
src/samples/3d/LayaAir3D_Advance/SeparableSSSRender/shader/SeparableSSS_Render.fs
src/samples/3d/LayaAir3D_Advance/SeparableSSSRender/shader/SeparableSSS_Render.vs

增加ＭｉｒｒｏｒＣｌａｐ纹理采样

---

src/layaAir/laya/d3/core/SkinnedMeshRenderer.ts
src/layaAir/laya/d3/core/render/RenderContext3D.ts
src/layaAir/laya/resource/BaseTexture.ts
src/layaAir/laya/resource/RenderTextureFormat.ts
src/samples/3d/LayaAir3D_Advance/SeparableSSS_RenderDemo.ts
src/samples/3d/LayaAir3D_PostProcess/PostProcess_AO/ScalableAO.ts
src/samples/3d/LayaAir3D_PostProcess/PostProcess_DoF/GaussianDoF.ts
src/samples/3d/LayaAirIDE/EditorShader/ParticleShuriKenPick.vs
src/samples/3d/LayaAirIDE/MouseInteraction/EditPickUtil.ts

渲染状态描述增加自定义shader以及替换Shader的架构

---

src/layaAir/laya/net/URL.ts

删除重复的if (url.indexOf(":") > 0) return url;

优化代码：删除多余的全路径判断

---

src/layaAir/laya/d3/core/Camera.ts
src/layaAir/laya/d3/core/render/command/BlitFrameBufferCMD.ts
src/layaAir/laya/d3/core/render/command/CommandBuffer.ts
src/layaAir/laya/d3/core/scene/Scene3D.ts
src/layaAir/laya/d3/graphics/IndexBuffer3D.ts

Perfect 3D custom resolution scheme

---

src/layaAir/laya/d3/component/Animator.ts

fux corssfade animator state bug

fix crossfade animatorevent bug

---

src/layaAir/laya/d3/animation/AnimationClip.ts
src/layaAir/laya/d3/component/PostProcess.ts

1、后期处理bug修复

---

src/layaAir/laya/d3/core/material/PBRStandardMaterial.ts
src/layaAir/laya/d3/core/scene/Scene3D.ts
src/layaAir/laya/d3/resource/models/SkyRenderer.ts
src/layaAir/laya/d3/shader/ShaderInit3D.ts
src/layaAir/laya/d3/shader/ShaderInstance.ts
src/layaAir/laya/webgl/WebGLContext.ts

修复cameraClearFlag为sky时 模板清除失效的bug
修复一些模板调用细节

补充其他材质支持模板缓存

---

src/layaAir/laya/d3/core/particleShuriKen/ShuriKenParticle3D.ts
src/layaAir/laya/d3/core/particleShuriKen/ShuriKenParticle3DShaderDeclaration.ts
src/layaAir/laya/d3/core/particleShuriKen/ShurikenParticleSystem.ts
src/layaAir/laya/d3/core/particleShuriKen/module/Emission.ts
src/layaAir/laya/d3/shader/files/ParticleShuriKen.vs

add Emition Distance

---

src/generateDoc/gulpfile.js
src/gulpfile.js

导出工具增加WebXR

---

src/layaAir/laya/d3/animation/AnimationClip.ts
src/layaAir/laya/d3/component/Animator.ts

fix  clip curveweight time bug

添加 AnimatorState.speed 解析，

---

src/layaAir/laya/d3/resource/RenderTexture.ts

修复RenderTexture设置属性之后的状态

---

src/layaAir/laya/d3/core/Camera.ts
src/layaAir/laya/d3/core/particleShuriKen/ShurikenParticleInstanceSystem.ts
src/layaAir/laya/d3/core/particleShuriKen/ShurikenParticleSystem.ts

修复粒子闪烁的bug
解析粒子simulateSpeed参数

修复动态修改粒子模块宏定义不匹配的bug

---

src/layaAir/laya/d3/core/BaseCamera.ts
src/layaAir/laya/d3/core/Camera.ts
src/layaAir/laya/d3/core/material/Material.ts
src/layaAir/laya/d3/core/scene/Scene3D.ts
src/layaAir/laya/d3/depthMap/DepthPass.ts
src/layaAir/laya/d3/shader/Shader3D.ts
src/layaAir/laya/d3/shadowMap/ShadowCasterPass.ts
src/layaAir/laya/layagl/LayaGLRunner.ts
src/layaAir/laya/webgl/utils/ShaderCompileDefineBase.ts

add BaseCamera UniformBuffer Update
add Scene UniformBuffer
add Scene UniformBuffer update
add DepthCast UniformBuffer
add DepthPass UniformBuffer Update
add ShadowMapCaster UniformBuffer Update

add BaseCamera UniformBuffer

---

src/layaAir/laya/d3/core/Camera.ts
src/layaAir/laya/d3/core/TransLargeUBOUtils.ts
src/layaAir/laya/d3/core/scene/Scene3D.ts
src/layaAir/laya/d3/depthMap/DepthPass.ts
src/layaAir/laya/d3/graphics/SubUniformBufferData.ts
src/layaAir/laya/d3/graphics/UniformBufferBase.ts
src/layaAir/laya/d3/graphics/UniformBufferData.ts
src/layaAir/laya/d3/graphics/UniformBufferObject.ts
src/layaAir/laya/d3/shader/ShaderInstance.ts
src/layaAir/laya/d3/shader/files/glslInput/DepthCasterInput.glsl
src/layaAir/laya/d3/shader/files/glslInput/LayaComInput.glsl
src/layaAir/laya/d3/shadowMap/ShadowCasterPass.ts
src/layaAir/laya/display/ShaderInstanceBase.ts

add SubUniformBufferData

---

src/layaAir/Laya3D.ts
src/layaAir/laya/d3/core/MeshRenderer.ts
src/layaAir/laya/d3/core/RenderableSprite3D.ts
src/layaAir/laya/d3/core/SimpleSkinnedMeshRenderer.ts
src/layaAir/laya/d3/core/SkinnedMeshRenderer.ts
src/layaAir/laya/d3/core/material/BlinnPhongMaterial.ts
src/layaAir/laya/d3/core/material/SkyPanoramicMaterial.ts
src/layaAir/laya/d3/core/reflectionProbe/ReflectionProbeManager.ts
src/layaAir/laya/d3/core/render/BaseRender.ts
src/layaAir/laya/d3/core/render/RenderElement.ts
src/layaAir/laya/d3/core/render/RenderQueue.ts
src/layaAir/laya/d3/core/render/command/DrawMeshCMD.ts
src/layaAir/laya/d3/core/render/command/DrawRenderCMD.ts
src/layaAir/laya/d3/resource/models/SubMesh.ts
src/layaAir/laya/d3/shader/ShaderData.ts
src/layaAir/laya/d3/shader/files/DepthNormalsTextureVS.vs
src/layaAir/laya/d3/shader/files/GlobalIllumination.glsl
src/layaAir/laya/d3/shader/files/Lighting.glsl
src/layaAir/laya/d3/shader/files/Mesh-BlinnPhong.vs
src/layaAir/laya/d3/shader/files/PBR.fs
src/layaAir/laya/d3/shader/files/PBR.vs
src/layaAir/laya/d3/shader/files/PBRLibs/PBRVSInput.glsl
src/layaAir/laya/d3/shader/files/ShadowCasterVS.glsl
src/layaAir/laya/d3/shader/files/WaterPrimary.fs
src/layaAir/laya/d3/shader/files/WaterPrimary.vs
src/layaAir/laya/d3/shader/files/extendTerrain.vs
src/samples/3d/LayaAir3D_Shader/customShader/glowingEdgeShader.vs
src/samples/3d/LayaAir3D_Shader/customShader/glowingEdgeShaderOutline.vs
src/samples/3d/LayaAir3D_Shader/customShader/outline02.vs
src/samples/3d/LayaAir3D_Shader/customShader/simpleShader.vs

change update by Sprite ShaderData

---

src/layaAir/laya/components/Component.ts
src/layaAir/laya/d3/WebXR/core/WebXRCamera.ts
src/layaAir/laya/d3/component/ComponentManager.ts
src/layaAir/laya/d3/component/Script3D.ts
src/layaAir/laya/d3/component/SimpleSingletonList.ts
src/layaAir/laya/d3/core/scene/Scene3D.ts
src/layaAir/laya/display/Node.ts
src/layaAir/laya/events/EventDispatcher.ts

Change Script Manager
add ComponentManager.ts
change Component Manager

Component Manager

---

src/layaAir/Laya3D.ts
src/layaAir/laya/d3/component/Animator.ts
src/layaAir/laya/d3/component/AnimatorResource.ts
src/layaAir/laya/d3/core/BaseCamera.ts
src/layaAir/laya/d3/core/Camera.ts
src/layaAir/laya/d3/core/FloatKeyframe.ts
src/layaAir/laya/d3/core/GeometryElement.ts
src/layaAir/laya/d3/core/MeshFilter.ts
src/layaAir/laya/d3/core/MeshRenderer.ts
src/layaAir/laya/d3/core/MeshSprite3D.ts
src/layaAir/laya/d3/core/RenderableSprite3D.ts
src/layaAir/laya/d3/core/SimpleSkinnedMeshRenderer.ts
src/layaAir/laya/d3/core/SimpleSkinnedMeshSprite3D.ts
src/layaAir/laya/d3/core/SkinnedMeshRenderer.ts
src/layaAir/laya/d3/core/SkinnedMeshSprite3D.ts
src/layaAir/laya/d3/core/Sprite3D.ts
src/layaAir/laya/d3/core/light/DirectionLight.ts
src/layaAir/laya/d3/core/light/DirectionLightCom.ts
src/layaAir/laya/d3/core/light/Light.ts
src/layaAir/laya/d3/core/light/LightQueue.ts
src/layaAir/laya/d3/core/light/LightSprite.ts
src/layaAir/laya/d3/core/light/PointLight.ts
src/layaAir/laya/d3/core/light/PointLightCom.ts
src/layaAir/laya/d3/core/light/SpotLight.ts
src/layaAir/laya/d3/core/light/SpotLightCom.ts

修改灯光为组件
删除Animator的连带Sprite3D
删除animatorAvatar
add FloatKeyframe.ts Clone
MeshFilter change component
MeshRender Change component
兼容Meshsprite3D
无效化RenderableSprite3D
SkinnedMeshRender change component
兼容SKinnedMeshSprite3D
整理Sprite3D
Dierctlight Change component
兼容Directlight Sprite3D
PointLight Change component
兼容Directlight Sprite3D
SpotLight Change component
兼容Directlight Sprite3D

修改渲染节点为渲染组件

---

src/layaAir/laya/d3/core/BaseCamera.ts
src/layaAir/laya/d3/core/Camera.ts
src/layaAir/laya/resource/Context.ts
src/samples/view/IndexView3D.ts

ios15.4闪屏的bug】

---

src/layaAir/laya/ani/bone/Skeleton.ts
src/layaAir/laya/d3/component/SimpleSingletonList.ts
src/layaAir/laya/d3/physics/PhysicsComponent.ts
src/layaAir/laya/device/media/HtmlVideo.ts
src/layaAir/laya/display/Sprite.ts

健壮simplesingletonlist remove函数
健壮physicsComponent的destroy函数
同步HTMLvideo作用域的bug
去除cache的问题

增加 skeleton的保护

---

src/layaAir/laya/webgl/text/CharRender_Canvas.ts

https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently

optimize: willReadFrequently setting for canvas

---

src/layaAir/laya/display/cmd/DrawTextureCmd.ts

fix: reset color property of DrawTextureCmd #192

---

src/layaAir/laya/d3/utils/Utils3D.ts
src/layaAir/laya/display/Animation.ts

fix:Fix the bug of wrong path acquisition when clone

---

src/layaAir/laya/d3/core/material/PBRMaterial.ts
src/layaAir/laya/d3/shader/pbr/pbrStandard.fs

refactor：PBR smoothness rule optimization

---

src/layaAir/laya/RenderEngine/RenderEngine/WebGLEngine/GLTextureContext.ts

fix：Fix the data parsing problem of KTX under WebGL1.

---

src/layaAir/Laya.ts
src/layaAir/laya/d3/shader/ShaderInstance.ts

fix：Fix stencilWrite typo.

---

src/layaAir/Laya.ts
src/layaAir/laya/d3/shader/ShaderInstance.ts

optimize: Optimize the initialization process of the engine.

---

gulpfile.js

注释中说 window 平台有未知魔法，这里没有进一步深究，把条件判断稍微调了一下来修复输出目录不对的问题

修正 linux 下构建脚本的逻辑

---

src/layaAir/laya/d3/core/Sprite3D.ts
src/layaAir/laya/display/Node.ts
src/layaAir/laya/ui/Tree.ts
src/layaAir/laya/ui/UIComponent.ts

- 可用于对节点添加标记
- 可用于兼容 unity 对象的 tag 属性
- 可选属性，用不到也不会影响现有功能

节点添加可选的 tag 属性

---

src/layaAir/laya/components/AnimationClip2D.ts
src/layaAir/laya/components/Animator2D.ts
src/layaAir/laya/components/AnimatorPlayState2D.ts
src/layaAir/laya/d3/animation/AnimationClip.ts
src/layaAir/laya/d3/component/Animator/Animator.ts
src/layaAir/laya/d3/component/Animator/AnimatorPlayState.ts
src/samples/index.ts

[fix:Fix the bug that sometimes the animation Event is not executed.](https://github.com/layabox/LayaAir/commit/5c201551e9cf083d88f5c65babb47fcc42d113f7)

Fix the bug that sometimes the animation Event is not executed

---

src/layaAir/laya/d3/core/particleShuriKen/ShurikenParticleInstanceSystem.ts

fix: Fix the memory leak of the instance particle system.

---

src/layaAir/laya/webgl/shader/d2/files/texture.ps.glsl
src/layaAir/laya/webgl/shader/d2/skinAnishader/skinShader.ps.glsl

fix: Fix the color space problem under bitmap.

---

src/layaAir/laya/net/Loader.ts

feat: Add subpackage loading interface of mini game platform.

---

src/layaAir/laya/ui/OpenDataContextView.ts

fix: Fix the display error problem of the open domain.

---

src/layaAir/laya/webgl/text/TextRender.ts

fix: Fix a parameter protection issue in TextRender.

---

src/layaAir/laya/d3/shader/depth/DepthVertex.glsl

修复: 修复webgl1下深度着色器的inverse函数报错问题.

fix: Fix the inverse function error reporting problem of the depth shader

---

src/layaAir/laya/net/Loader.ts

fix: Fix the error that the mini-game subpackage loading progress function.

---

src/layaAir/laya/RenderEngine/RenderEngine/WebGLEngine/GLShaderInstance.ts

修复: 修复WebGL2RenderContext在小游戏平台未定义的问题.

fix: Fix the problem that WebGL2RenderContext is not defined on the minigame

---

src/layaAir/laya/RenderEngine/RenderEngine/WebGLEngine/GLShaderInstance.ts

修复: 修复WebGL2RenderContext在小游戏平台未定义的问题.

fix: Fix the problem that WebGL2RenderContext is not defined on the minigame.

---

src/layaAir/laya/d3/shader/ShurikenParticle/ParticleShuriKenShaderInit.ts
src/layaAir/laya/d3/shader/ShurikenParticle/particleShuriKen.fs

optimize: add AlphaTest renderMode in Particle

---

src/layaAir/laya/resource/Context.ts

fix: Fix the problem that the Grid setting is invalid.

---

src/layaAir/laya/net/URL.ts

fix: Fix the skel file suffix problem of ByteDance mini game.

---

src/layaAir/laya/media/VideoTexture.ts

fix: Fix video tag playable type error.

---

src/layaAir/laya/d3/core/UI3D/UI3D.ts

feat: Added culling mode option for UI3D.

---

src/samples/Main.ts

test：Modify the loading method of fileconfig.json.

---

src/layaAir/laya/ui/OpenDataContextView.ts

fix: Fix openDataContext color space error.

---

src/layaAir/laya/d3/core/SkinnedMeshRenderer.ts

fix: Fixed morph target protection for skinned renderer.

---

src/layaAir/laya/d3/core/render/BaseRender.ts
src/layaAir/laya/d3/graphics/Batch/RenderElementBatch.ts

fix: Fix lightmap event update mechanism issue.

---

src/layaAir/laya/d3/core/UI3D/UI3D.ts

fix: Fix UI3D resource destruction error reporting problem.

---

src/layaAir/laya/RenderEngine/RenderShader/ShaderData.ts

optimize: Optimize the process of ubo when cloning shaderData.

---

src/layaAir/laya/d3/ModuleDef.ts
src/layaAir/laya/d3/core/render/PostEffect/LensFlares/LensFlareCMD.ts
src/layaAir/laya/d3/core/render/PostEffect/LensFlares/LensFlareEffect.ts
src/layaAir/laya/d3/core/render/PostEffect/LensFlares/LensFlareGeometry.ts
src/layaAir/laya/d3/core/render/PostEffect/LensFlares/LensFlareShaderInit.ts
src/layaAir/laya/d3/loaders/LensFlareSettingsLoader.ts
src/layaAir/laya/d3/shader/files/postProcess/LensFlare/LensFlare.fs
src/layaAir/laya/d3/shader/files/postProcess/LensFlare/LensFlare.vs
src/samples/Main.ts

feat: Add LensFlare post-processing function.

---

src/layaAir/laya/d3/core/render/PostEffect/LensFlares/LensFlareCMD.ts
src/layaAir/laya/d3/core/render/PostEffect/LensFlares/LensFlareEffect.ts
src/layaAir/laya/d3/core/render/PostEffect/LensFlares/LensFlareShaderInit.ts
src/layaAir/laya/d3/loaders/LensFlareSettingsLoader.ts
src/layaAir/laya/d3/shader/files/postProcess/LensFlare/LensFlare.vs
src/samples/3d/LayaAir3D_PostProcess/PostPorcess_LensFlare.ts
src/samples/view/IndexView3D.ts

fix: Fixed LensFlare scaling bug.

---

gulpfile.js
src/layaAir/laya/Physics3D/Bullet/Collider/btCollider.ts

fix: Fix Rigidbody Cancollision set error.

---

gulpfile.js
src/layaAir/jsLibs/laya.physics3D.js
src/layaAir/laya/Physics3D/PhysX/Collider/pxDynamicCollider.ts
src/layaAir/laya/d3/ModuleDef.ts
src/layaAir/laya/d3/physics/ModuleDef.ts

fix: Fix issue with exporting 3d physics.

---

src/layaAir/laya/d3/core/UI3D/UI3D.ts
src/layaAir/laya/d3/core/UI3D/UI3DGeometry.ts

fix: Fix UI3D scale cull error.

---

src/layaAir/laya/ui/UIComponent.ts
src/layaAir/laya/webgl/shader/d2/value/Value2D.ts

fix:Fix the bug that synchronization of disabled and gray of UIComponent causes ide to be unable to update properties separately.(修复UIComponent的disabled和gray同步导致ide无法分开更新属性的bug)

:Fix the bug that synchronization of disabled and gray of UIComponent causes ide to be unable to update properties separately

---

src/layaAir/jsLibs/spine-core-3.8.js

更新spine3.8官方库，修正了切换动画的时候有些骨骼图片会丢失显示的bug

Laya air 3.0.0（更新spine3.8官方库，修正了切换动画的时候有些骨骼图片会丢失显示的bug）

---

src/layaAir/laya/Physics3D/Bullet/Collider/btRigidBodyCollider.ts
src/layaAir/laya/Physics3D/Bullet/Shape/btCapsuleColliderShape.ts
src/layaAir/laya/Physics3D/Bullet/Shape/btConeColliderShape.ts
src/layaAir/laya/Physics3D/Bullet/Shape/btCylinderColliderShape.ts
src/layaAir/laya/Physics3D/Bullet/Shape/btSphereColliderShape.ts
src/layaAir/laya/Physics3D/PhysX/Collider/pxCollider.ts
src/layaAir/laya/Physics3D/PhysX/Collider/pxDynamicCollider.ts
src/layaAir/laya/Physics3D/PhysX/Collider/pxStaticCollider.ts
src/layaAir/laya/Physics3D/PhysX/Shape/pxBoxColliderShape.ts
src/layaAir/laya/Physics3D/PhysX/Shape/pxCapsuleColliderShape.ts
src/layaAir/laya/Physics3D/PhysX/Shape/pxColliderShape.ts
src/layaAir/laya/Physics3D/PhysX/Shape/pxSphereColliderShape.ts
src/layaAir/laya/d3/physics/PhysicsCollider.ts
src/layaAir/laya/d3/physics/PhysicsColliderComponent.ts
src/layaAir/laya/d3/physics/Rigidbody3D.ts
src/layaAir/laya/d3/physics/shape/BoxColliderShape.ts
src/layaAir/laya/d3/physics/shape/CapsuleColliderShape.ts
src/layaAir/laya/d3/physics/shape/ConeColliderShape.ts
src/layaAir/laya/d3/physics/shape/CylinderColliderShape.ts
src/layaAir/laya/d3/physics/shape/SphereColliderShape.ts
src/layaAir/laya/d3/utils/Physics3DUtils.ts

fix: Fix PhysicsComponent dispatch event error.

---

gulpfile.js

fix: Fix Compile error.

---

src/layaAir/laya/events/Event.ts

fix: Fixed the problem of script component onMouseDrag not triggering.

---

src/layaAir/laya/d3/shader/ShurikenParticle/MathGradient.glsl

fix: Fixed the problem of black edges appearing on particles on iOS.

---

src/layaAir/jsLibs/bullet.js
src/layaAir/jsLibs/physx.release.js
src/layaAir/laya/Physics3D/Bullet/Collider/btRigidBodyCollider.ts
src/layaAir/laya/d3/physics/ModuleDef.ts
src/layaAir/laya/d3/physics/PhysicsColliderComponent.ts

Fix: Fixed issue with bullet reloading gravity.

---

src/layaAir/laya/Physics3D/Bullet/btPhysicsManager.ts

Fix: Fixed the AABB collision problem of bullet character controller.

修复: 修复bullet角色控制器AABB碰撞问题.

---

src/layaAir/Laya.ts

fix: Fix the problem that the Alipay minigame srgb ext.

---

src/layaAir/laya/Physics3D/Bullet/Shape/btBoxColliderShape.ts
src/layaAir/laya/Physics3D/PhysX/Joint/pxJoint.ts

fix: Fixed the Bullet’s Box scaling logic error.

---

src/layaAir/laya/webgl/submit/SubmitTarget.ts

fix: Fixed the problem of blur filter color being white.

---

src/layaAir/laya/d3/core/scene/Scene3D.ts

fix: Remove unused attribute content.

---

bin/rollUp.html
gulpfile.js
package.json

feta: Add the compilation and construction process of the example.

---

src/extensions/debug/tools/Base64Tool.ts
src/layaAir/Laya.ts
src/layaAir/jsLibs/spine-core-3.7.js
src/layaAir/jsLibs/spine-core-3.8.js
src/layaAir/jsLibs/spine-core-4.0.js
src/layaAir/laya/d3/graphics/SphericalHarmonicsL2.ts
src/layaAir/laya/display/Stage.ts
src/layaAir/laya/webgl/text/CharRender_Canvas.ts

feat: Increase the adaptation of Taobao mini games.

---

src/layaAir/laya/d3/physics/PhysicsUpdateList.ts

fix: Fix bug in physics update list.

---

src/layaAir/jsLibs/laya.tbappmini.js
src/layaAir/jsLibs/laya.tbmini.js
src/layaAir/laya/renders/Render.ts

feat: Adapt to Taobao widgets and mini programs.

---

src/layaAir/laya/display/Graphics.ts
src/layaAir/laya/display/cmd/DrawGeoCmd.ts
src/layaAir/laya/renders/Context.ts
src/layaAir/laya/spine/SpineSkeleton.ts
src/layaAir/laya/spine/SpineSkeletonRenderer.ts
src/layaAir/laya/spine/SpineTemplet.ts
src/layaAir/laya/spine/SpineVirtualMesh.ts
src/layaAir/laya/spine/files/textureSpine.ps.glsl
src/layaAir/laya/spine/files/textureSpine.vs.glsl
src/layaAir/laya/spine/material/SpineMaterial.ts
src/layaAir/laya/spine/material/SpineMaterialShaderInit.ts

Spine optimize

---

gulpfile.js
src/layaAir/laya/RenderDriver/DriverDesign/RenderDevice/IRenderEngine.ts
src/layaAir/laya/RenderEngine/UniformBufferObject.ts
src/layaAir/tsconfig.json

style: Modify the export directory and separate the rendering device

---

gulpfile.js

修复: 修复RuntimeRenderData导出目录错误问题.

fix: Fixed RuntimeRenderData export directory error issue.

---

gulpfile.js
src/layaAir/laya/Physics3D/Bullet/btPhysicsManager.ts
src/layaAir/laya/Physics3D/PhysX/pxPhysicsManager.ts
src/layaAir/laya/RenderDriver/WebGLDriver/3DRenderPass/WebGLDirectLightShadowRP.ts
src/layaAir/laya/RenderDriver/WebGLDriver/3DRenderPass/WebGLForwardAddClusterRP.ts
src/layaAir/laya/RenderDriver/WebGLDriver/3DRenderPass/WebGLRender3DProcess.ts
src/layaAir/laya/RenderDriver/WebGLDriver/3DRenderPass/WebGLSpotLightShadowRP.ts
src/layaAir/laya/d3/component/Animator/Animator.ts
src/layaAir/laya/d3/core/Camera.ts
src/layaAir/laya/d3/core/SkinnedMeshRenderer.ts
src/layaAir/laya/d3/core/particleShuriKen/ShurikenParticleRenderer.ts

fix 修复在执行buildPerf任务时, json路径输出错误的问题
feat 增加导出性能统计分析的gulp任务, 将原来的性能统计注释修改到JsDoc中

Manual Merge commit from "LayaAir3.0Native" to "Master3.0"

---

src/layaAir/laya/display/Stage.ts
src/layaAir/laya/renders/Render2D.ts
src/layaAir/laya/tools/PerformanceTool.ts

Fixed issue # 把stage中的render2d提取出来，方便性能统计，移除PerformanceTool中老方案的代码
Fixed issue # 修改变量名

Fixed issue # 合并代码

---

src/layaAir/laya/d3/WebXR/core/WebXRExperienceHelper.ts

fix: Fix LayaGL is not import.

---

src/layaAir/laya/spine/SpineAdapter.ts
src/layaAir/laya/spine/SpineSkeletonRenderer.ts
src/layaAir/laya/spine/SpineTemplet.ts
src/layaAir/laya/spine/optimize/AnimationRender.ts
src/layaAir/laya/spine/optimize/AttachmentParse.ts
src/layaAir/laya/spine/optimize/SketonOptimise.ts
src/layaAir/laya/spine/optimize/SlotUtils.ts
src/layaAir/laya/spine/slot/SlotExtend.ts
src/layaAir/laya/spine/slot/SlotExtendRG.ts

fix: adapter Taobao minigame spine issue.

---

src/layaAir/laya/RenderDriver/WebGPUDriver/2DRenderPass/WebGPURenderElement2D.ts
src/layaAir/laya/RenderDriver/WebGPUDriver/3DRenderPass/WebGPU3DRenderPassFactory.ts
src/layaAir/laya/RenderDriver/WebGPUDriver/3DRenderPass/WebGPURenderCMD/WebGPUDrawElementCMDData.ts
src/layaAir/laya/RenderDriver/WebGPUDriver/3DRenderPass/WebGPURenderCMD/WebGPUSetShaderDefine.ts
src/layaAir/laya/RenderDriver/WebGPUDriver/3DRenderPass/WebGPURenderCMD/WebGPUSetViewportCMD.ts
src/layaAir/laya/RenderDriver/WebGPUDriver/3DRenderPass/WebGPURenderContext3D.ts
src/layaAir/laya/RenderDriver/WebGPUDriver/3DRenderPass/WebGPURenderElement3D.ts
src/layaAir/laya/RenderDriver/WebGPUDriver/3DRenderPass/WebGPUSkinRenderElement3D.ts
src/layaAir/laya/RenderDriver/WebGPUDriver/RenderDevice/WebGPUBundle/WebGPURenderBundle.ts
src/layaAir/laya/RenderDriver/WebGPUDriver/RenderDevice/WebGPUBundle/WebGPURenderBundleManager.ts
src/layaAir/laya/RenderDriver/WebGPUDriver/RenderDevice/WebGPUBundle/WebGPURenderBundleManagerSet.ts
src/layaAir/laya/RenderDriver/WebGPUDriver/RenderDevice/WebGPUCodeGenerator.ts
src/layaAir/laya/RenderDriver/WebGPUDriver/RenderDevice/WebGPURenderCommandEncoder.ts
src/layaAir/laya/RenderDriver/WebGPUDriver/RenderDevice/WebGPURenderDeviceFactory.ts
src/layaAir/laya/RenderDriver/WebGPUDriver/RenderDevice/WebGPURenderPipelineHelper.ts
src/layaAir/laya/RenderDriver/WebGPUDriver/RenderDevice/WebGPUShaderInstance.ts
src/layaAir/laya/RenderDriver/WebGPUDriver/RenderDevice/WebGPUStatis/WebGPUGlobal.ts
src/layaAir/laya/RenderDriver/WebGPUDriver/RenderDevice/WebGPUVertexBuffer.ts

支持Stencil，调整bundle，优化缓存，输出更详细调试信息。

更新WebGPU代码

---

src/layaAir/laya/d3/ModuleDef.ts
src/layaAir/laya/d3/physics/PhysicsColliderComponent.ts

fix: Fix collider Add to scene.

---

src/layaAir/laya/webgl/text/CharRender_Canvas.ts

fix: Fixed the problem of custom font in Alipay mini game.

---

src/layaAir/laya/net/URL.ts

fix: Fix extension loading of lavm files.

---

src/layaAir/laya/Physics3D/Bullet/btPhysicsManager.ts
src/layaAir/laya/Physics3D/PhysX/pxPhysicsManager.ts

fix: Fixed the problem of reuse of physical component collider.

---

src/layaAir/laya/spine/optimize/AnimationRender.ts
src/layaAir/laya/spine/optimize/SpineInstanceBatch.ts
src/layaAir/laya/spine/optimize/VBCreator.ts
src/layaAir/laya/spine/optimize/change/ChangeDeform.ts

fix: 
1.Change the BufferState object to a per-RenderElement basis.
2. frameIndex miscalculated.(当前帧计算错误)
feat: 
1. Spine support ChangeDeform.(支持顶点变换)

spine update

---

src/layaAir/laya/display/Scene2DSpecial/Camera2D.ts
src/samples/2d/Camera2DDemo.ts
src/samples/3d/LayaAir3D_Resource/GarbageCollection.ts

fix: Fixed the problem of adding scene in Camera2D.

---

src/layaAir/laya/spine/optimize/SketonOptimise.ts

fix: All AttachmentParse should be counted to confirm the type.

---

src/samples/2d/Network_GET.ts
src/samples/2d/Network_POST.ts
src/samples/2d/Network_Socket.ts
src/samples/2d/Network_Socket2.ts

test: Fixed problem with network format example address.

---

src/layaAir/laya/utils/Browser.ts

feat: Add OpenHarmonyOS flag.

---

src/layaAir/laya/d3/physics/PhysicsColliderComponent.ts

fix: Fixed collision group setting method call error.

---

src/layaAir/laya/webgl/text/CharRender_Canvas.ts

fix: Fixed text cropping problem in WeChat IOShighperformanceplus mode.

---

src/layaAir/laya/renders/RenderSprite.ts

修复: 修复ctx缓存到RenderTexture2D的清理流程.

fix: Fix the cleanup process of ctx cache to RenderTexture2D.

---

src/layaAir/laya/RenderDriver/WebGLDriver/3DRenderPass/WebGLDirectLightShadowRP.ts
src/layaAir/laya/RenderDriver/WebGLDriver/3DRenderPass/WebGLSpotLightShadowRP.ts

修复: 修复WebGL上InstanceBatch内存泄漏问题.

fix: Fixed WebGL InstanceBatch memory leak issue.

---

src/layaAir/laya/spine/Spine2DRenderNode.ts
src/layaAir/laya/spine/SpineSkeleton.ts
src/layaAir/laya/spine/optimize/AttachmentParse.ts
src/layaAir/laya/spine/optimize/SketonOptimise.ts
src/layaAir/laya/spine/optimize/SlotUtils.ts
src/layaAir/laya/spine/optimize/SpineBakeScript.ts
src/layaAir/laya/spine/optimize/SpineOptimizeRender.ts
src/layaAir/laya/spine/optimize/VBCreator.ts

1.Fixed an issue where animations would not play the default animation number 0(修复动画不会播放默认0号动画的问题) 
2.Adjust the animation boneGPU priority（调整骨骼动画的优先级）
3.Fixed an issue with the timing of the baking animation initialization(修复烘培动画初始化时序问题)
4.support spine PathAttachment

fix: about spine

---

src/layaAir/laya/spine/Spine2DRenderNode.ts

fix:Set the node.source And then destroy errors caused by node before loading is complete.（健壮性）

fix: spine bug

---

src/layaAir/laya/RenderDriver/DriverCommon/RenderListQueue.ts

fix: Restore the commit of recoverData.

---

src/layaAir/laya/RenderDriver/WebGPUDriver/3DRenderPass/WebGPUSkinRenderElement3D.ts
src/layaAir/laya/RenderDriver/WebGPUDriver/RenderDevice/WebGPUShaderData.ts

修改 WebGPU Bug: 因为骨骼渲染数据更新时没有清理队列，造成逐渐掉帧

---

src/layaAir/laya/spine/Spine2DRenderNode.ts

fix: Adjust the logic for handling resources after preloading.

---

src/layaAir/Laya.ts
src/layaAir/laya/Physics3D/Bullet/Collider/btCharacterCollider.ts
src/layaAir/laya/Physics3D/Bullet/Collider/btRigidBodyCollider.ts
src/layaAir/laya/Physics3D/Bullet/Collider/btStaticCollider.ts
src/layaAir/laya/Physics3D/Bullet/Joint/btCustomJoint.ts
src/layaAir/laya/Physics3D/Bullet/Joint/btFixedJoint.ts
src/layaAir/laya/Physics3D/Bullet/Joint/btHingeJoint.ts
src/layaAir/laya/Physics3D/Bullet/Joint/btJoint.ts
src/layaAir/laya/Physics3D/Bullet/Joint/btSpringJoint.ts
src/layaAir/laya/Physics3D/Bullet/btPhysicsManager.ts
src/layaAir/laya/Physics3D/PhysX/Collider/pxCharactorCollider.ts
src/layaAir/laya/Physics3D/PhysX/Collider/pxDynamicCollider.ts
src/layaAir/laya/Physics3D/PhysX/Collider/pxStaticCollider.ts
src/layaAir/laya/Physics3D/PhysX/Joint/PxFixedJoint.ts
src/layaAir/laya/Physics3D/PhysX/Joint/pxD6Joint.ts
src/layaAir/laya/Physics3D/PhysX/Joint/pxDistanceJoint.ts
src/layaAir/laya/Physics3D/PhysX/Joint/pxJoint.ts
src/layaAir/laya/Physics3D/PhysX/Joint/pxRevoluteJoint.ts
src/layaAir/laya/Physics3D/PhysX/pxPhysicsManager.ts
src/layaAir/laya/Physics3D/interface/IPhysicsManager.ts
src/layaAir/laya/Physics3D/interface/Joint/IJoint.ts
src/layaAir/laya/Physics3D/interface/Physics3DStatInfo.ts
src/layaAir/laya/Physics3D/physicsEnum/EPhysicsStatisticsInfo.ts
src/layaAir/laya/d3/ModuleDef.ts
src/layaAir/laya/d3/physics/ModuleDef.ts
src/layaAir/laya/d3/physics/constraints/ConstraintComponent.ts

fix: Add Physical Statistics Functionality.

---

src/layaAir/Laya.ts
src/layaAir/Laya3D.ts
src/layaAir/laya/Physics3D/interface/Physics3DStatInfo.ts
src/layaAir/laya/utils/Stat.ts

修复: 分离Stat与Physics3DStatisticsInfo

fix: Separate Stat and Physics3DStatisticsInfo

---

src/layaAir/laya/Physics3D/interface/Physics3DStatInfo.ts

fix: Increase whether to clear the statistics flag every frame.

---

src/layaAir/laya/Physics3D/Bullet/Collider/btStaticCollider.ts
src/layaAir/laya/Physics3D/Bullet/btPhysicsManager.ts
src/layaAir/laya/Physics3D/PhysX/Collider/pxCharactorCollider.ts
src/layaAir/laya/Physics3D/PhysX/Collider/pxCollider.ts
src/layaAir/laya/Physics3D/PhysX/Collider/pxDynamicCollider.ts
src/layaAir/laya/Physics3D/PhysX/Shape/pxCapsuleColliderShape.ts
src/layaAir/laya/Physics3D/PhysX/pxCollisionTool.ts
src/layaAir/laya/Physics3D/PhysX/pxPhysicsManager.ts
src/layaAir/laya/d3/physics/CharacterController.ts
src/layaAir/laya/d3/physics/PhysicsCollider.ts
src/layaAir/laya/d3/physics/PhysicsColliderComponent.ts
src/layaAir/laya/d3/physics/Rigidbody3D.ts

fix: Fixed issue with physics prefab instantiation errors.

---

src/layaAir/laya/display/Sprite.ts

Calculate correct width and height after sprite.graphics initialization.(在sprite.graphics初始化之后，正确的计算宽高)

fix:spine bug.

---

src/layaAir/laya/Physics3D/PhysX/pxPhysicsManager.ts

fix: Fixed the problem of updating the position of the rigid body first add.

---

src/layaAir/laya/spine/Spine2DRenderNode.ts
src/layaAir/laya/spine/SpineTemplet.ts

1.Removing redundant animation name tracking.(移除多余的_curAniName) 
2.Fixing template switching animation playback(修复切换templete无法播放当前同名动画的问题) 
3.Cleaning up and organizing event handling.(整理相关事件)

Fix:Spine bug

---

gulpfile.js

fix: remove physx js lib .mem file publish.

---

src/layaAir/laya/d3/core/UI3D/UI3D.ts
src/layaAir/laya/d3/core/scene/Input3D.ts

修复UI3DdrawToRenderTexture2D与Input3D点击位置转换问题.

fix UI3D drawToRenderTexture2D and Input3D point trans error.

---

src/layaAir/laya/Physics3D/Bullet/btPhysicsManager.ts

fix: Wrong modification of reset bullet process.

---

src/layaAir/laya/d3/core/Camera.ts

fix: Fixed the issue with viewport coordinate conversion.

---

src/layaAir/laya/webgl/text/CharRender_Canvas.ts

fix: Fixed the problem of incorrect text size measurement in mini-games.

---

src/layaAir/laya/display/Scene.ts

Fix: Add global shaderData acquisition on Scene.

---

src/layaAir/laya/display/Scene2DSpecial/TileMap/ModuleDef.ts
src/layaAir/laya/display/Scene2DSpecial/TileMap/TileAlternativesData.ts
src/layaAir/laya/display/Scene2DSpecial/TileMap/TileMapChunkData.ts
src/layaAir/laya/display/Scene2DSpecial/TileMap/TileMapEnum.ts
src/layaAir/laya/display/Scene2DSpecial/TileMap/TileMapLayer.ts
src/layaAir/laya/display/Scene2DSpecial/TileMap/TileMapPhysics.ts
src/layaAir/laya/display/Scene2DSpecial/TileMap/TileSet.ts
src/layaAir/laya/display/Scene2DSpecial/TileMap/TileSetCellData.ts
src/layaAir/laya/spine/Spine2DRenderNode.ts
src/layaAir/laya/spine/files/SpineFragment.glsl
src/layaAir/laya/spine/files/SpineStandard.vs
src/layaAir/laya/spine/material/SpineShaderInit.ts
src/layaAir/laya/spine/mesh/SpineWasmVirturalMesh.ts
src/layaAir/laya/spine/optimize/SpineNormalRender.ts
src/layaAir/laya/spine/optimize/SpineOptimizeRender.ts

1. Split dirtyflag.(拆分 dirtyflag)
2. Physical optimization for chunk by chunk.(物理优化为逐chunk)
3. merging and organization.(合并代码后调整)
4. Organize code.(整理代码)

Spine And Tile

---

src/layaAir/laya/display/Scene2DSpecial/Light2D/Light2DManager.ts

CommandBuffer2D类的函数名称发生改变，drawMesh2DByMatrix 更改为 drawMesh，Light2DManager中相关调用改成相应的名称。

drawMesh2DByMatrix 更改为 drawMesh

---

src/samples/2d/Material2DDemo.ts
src/samples/2d/Physics_Bridge.ts
src/samples/2d/Physics_Strandbeests.ts
src/samples/view/IndexView2D.ts
src/samples/view/IndexView3D.ts

test: Add custom material examples and configure 2D sample content.

---

src/samples/2d/BlendMode_Lighter.ts
src/samples/2d/Network_GET.ts
src/samples/2d/Network_POST.ts
src/samples/2d/Network_Socket2.ts
src/samples/2d/RenderCMD2DDemo.ts
src/samples/3d/LayaAir3D_Physics3D/PhysicsWorld_RayShapeCast.ts

test: Modify the test example content.

---

scripts/config.mjs
src/layaAir/laya/d3/core/UI3D/UI3D.ts

fix: Fixed the problem of sprite destruction error reporting in UI3D.

---

scripts/config.mjs

fix: Fixed the issue of trail library release configuration error.

---

src/layaAir/laya/d3/physics/CharacterController.ts
src/layaAir/laya/d3/physics/PhysicsCollider.ts
src/layaAir/laya/d3/physics/PhysicsColliderComponent.ts
src/layaAir/laya/d3/physics/Rigidbody3D.ts
src/layaAir/laya/d3/physics/constraints/ConfigurableConstraint.ts
src/layaAir/laya/d3/physics/constraints/ConstraintComponent.ts
src/layaAir/laya/d3/physics/constraints/FixedConstraint.ts
src/layaAir/laya/d3/physics/constraints/HingeConstraint.ts
src/layaAir/laya/d3/physics/constraints/SpringConstraint.ts
src/layaAir/laya/display/Node.ts

optimize: Optimize Node event dispatching.

---

src/layaAir/laya/navigation/common/component/BaseNavMeshSurface.ts
src/samples/view/IndexView2D.ts

fix: Fixed the problem of navMesh baking error when modifying tile size.

---

src/layaAir/laya/display/Scene2DSpecial/TileMap/TileMapChunkData.ts
src/layaAir/laya/display/Scene2DSpecial/TileMap/loaders/TileSetAssetLoader.ts

fix：Add protection for deleting corresponding tiles from tileSet

---

src/layaAir/laya/tilemap/RectClipper.ts
src/layaAir/laya/tilemap/TileMapChunkData.ts
src/layaAir/laya/tilemap/TileMapLayer.ts
src/layaAir/laya/tilemap/TileMapOccluderAgent.ts
src/layaAir/laya/webgl/shader/d2/NewShader/Sprite2DVertex.glsl

1.Fix the issue where lightOccluder cannot be closed.（修复 lightOccluder 无法关闭的问题） 
2.Reduce the number of objects that need to be updated in transform.（transform 变化需要更新的对象减少）

fix: TileMap bug

---

src/layaAir/Laya.ts

fix: Fixed isAlpha transparency error issue.

---

src/layaAir/laya/resource/Texture2D.ts
src/layaAir/laya/spine/SpineTemplet.ts
src/layaAir/laya/spine/SpineTempletLoader.ts
src/layaAir/laya/spine/files/SpineStandard.vs
src/layaAir/laya/spine/material/SpineShaderInit.ts
src/layaAir/laya/spine/normal/SpineSkeletonRenderer.ts
src/layaAir/laya/spine/optimize/AttachmentParse.ts
src/layaAir/laya/spine/optimize/change/ChangeRGBA.ts

Check image pre multiplication to determine if spine has enabled premultipliedAlpha.(检查图片预乘来判断spine是否开启预乘)

spine关于预乘的同步

---

src/layaAir/laya/physics/RigidBody.ts

fix: Fixed rigid body enable error issue.

---

src/layaAir/laya/spine/Spine2DRenderNode.ts

fix:Cleaning up when stopping causes switching animation errors

---

src/layaAir/laya/spine/Spine2DRenderNode.ts
src/layaAir/laya/spine/files/SpineVertex.glsl

fix:
1.Cleaning up when stopping causes switching animation errors.
2.Display position error in CAMERA2D state.

Fix Spine Bug

---

src/layaAir/laya/d3/shader/ShurikenParticle/particleShuriKen.vs
src/layaAir/laya/d3/shader/ShurikenParticle/particleShuriKenSpriteVS.glsl

fix: Fix shurikenparticle mulDefineMode shader compile error.

---

src/layaAir/laya/physics/RigidBody.ts

fix: Fixed the problem of incorrect rigid body position.

---

src/layaAir/laya/physics/RigidBody.ts

fix: Temporarily fix the physical lag issue.

---

src/layaAir/laya/Light2D/Light2DManager.ts

fix: Fixed 2D lighting configuration initialization error issue.

---

src/layaAir/laya/d3/core/Camera.ts

fix: fixed: ray function dont change input of inParam.

---

.vscode/launch.json
bin/rollUp.html
bin/rollUp/bundle.js
bin/spine-core-3.8.js
gulpfile.js
package.json
src/layaAir/laya/spine/optimize/AnimationRender.ts
src/layaAir/laya/spine/optimize/SpineOptimizeRender.ts
src/samples/2d/Physics_CollisionFiltering.ts
src/samples/Entrance.ts
src/samples/tsconfig.json

fix:Material cannot be used as a judgment on whether to reorganize rendering data.(material不能作为是否需要重新组织渲染数据的判断)

fix:3.2.3 Spine bug

---

src/layaAir/laya/tilemap/ModuleDef.ts
src/layaAir/laya/tilemap/TileMapChunkData.ts
src/layaAir/laya/tilemap/TileMapLayer.ts
src/layaAir/laya/tilemap/TileMapPhysics.ts
src/layaAir/laya/tilemap/TileSet.ts
src/layaAir/laya/tilemap/TileSetCellData.ts
src/layaAir/laya/tilemap/layers/TileSetTerrainLayer.ts
src/layaAir/laya/tilemap/layers/TileSetTerrainSet.ts
src/layaAir/laya/tilemap/loaders/TileSetAssetLoader.ts
src/layaAir/laya/tilemap/terrain/TileMapTerrain.ts
src/layaAir/laya/tilemap/terrain/TileMapTerrainUtils.ts

optimize:Modification of physical update method.(物理更新方式修改)
feat:Update on Tile Terrains.(更新Tile Terrains)

TileMap Update

---

src/layaAir/laya/Light2D/Light2DConfig.ts
src/layaAir/laya/Light2D/Light2DManager.ts

optimize: Optimize the initialization process of 2D lighting settings.

---

src/layaAir/laya/particle/d3/module/shape/ShapeUtils.ts

fix: Fixed the problem of particle non-random seed emission error.

---

src/layaAir/laya/physics/RigidBody.ts

fix: Fixed 2D physics rigid body transformation update error issue.

---

src/layaAir/laya/d3/resource/models/Mesh.ts
src/layaAir/laya/physics/IPhysiscs2DFactory.ts
src/layaAir/laya/physics/RigidBody.ts
src/layaAir/laya/physics/factory/physics2DwasmFactory.ts

fix: Fixed synchronization issue after Mesh modification.

---

src/layaAir/jsLibs/spine-core-4.2.js
src/layaAir/laya/spine/Spine2DRenderNode.ts
src/layaAir/laya/spine/SpineTemplet.ts
src/layaAir/laya/spine/SpineTempletLoader.ts
src/layaAir/laya/spine/mesh/SpineMeshBase.ts
src/layaAir/laya/spine/normal/SpineSkeletonRenderer.ts
src/layaAir/laya/spine/normal/SpineWasmRender.ts
src/layaAir/laya/spine/optimize/AnimationRender.ts
src/layaAir/laya/spine/optimize/AnimationRenderProxy.ts
src/layaAir/laya/spine/optimize/SketonOptimise.ts
src/layaAir/laya/spine/optimize/SpineOptimizeRender.ts
src/layaAir/laya/spine/optimize/VBCreator.ts
src/layaAir/laya/tilemap/TileMapChunkData.ts
src/layaAir/laya/tilemap/TileSet.ts
src/layaAir/laya/tilemap/layers/TileSetTerrainSet.ts
src/layaAir/laya/tilemap/terrain/TileMapTerrain.ts
src/layaAir/laya/tilemap/terrain/TileMapTerrainUtils.ts
src/layaAir/tslibs/spine.d.ts

feat: Support spine 4.2
optimize : TileMapLayer serialize.

Update Spine And TileMap

---

src/layaAir/laya/spine/Spine2DRenderNode.ts

设置Skeleton.xy应该使用sprite的global.xy

fix: Setting Skeleton.xy should use the global.xy of sprite.(

---

src/layaAir/laya/physics/Collider2D/ColliderBase.ts
src/layaAir/laya/physics/ModuleDef.ts
src/layaAir/laya/physics/Physics2DWorldManager.ts
src/layaAir/laya/physics/RigidBody.ts
src/layaAir/laya/physics/Shape/BoxShape2D.ts
src/layaAir/laya/physics/Shape/ChainShape2D.ts
src/layaAir/laya/physics/Shape/CircleShape2D.ts
src/layaAir/laya/physics/Shape/EdgeShape2D.ts
src/layaAir/laya/physics/Shape/Physics2DShapeBase.ts
src/layaAir/laya/physics/Shape/PolygonShape2D.ts
src/layaAir/laya/physics/StaticCollider.ts
src/layaAir/laya/physics/factory/IPhysics2DFactory.ts
src/layaAir/laya/physics/factory/physics2DwasmFactory.ts
src/samples/2d/Physics_Bridge.ts
src/samples/2d/Physics_Bridge_Shapes.ts
src/samples/2d/Physics_CollisionEvent.ts
src/samples/2d/Physics_CollisionEvent_Shapes.ts
src/samples/2d/Physics_CollisionFiltering.ts
src/samples/2d/Physics_CollisionFiltering_Shapes.ts
src/samples/2d/Physics_Strandbeests.ts
src/samples/2d/Physics_Strandbeests_Shapes.ts
src/samples/2d/Physics_Tumbler.ts
src/samples/2d/Physics_Tumbler_Shapes.ts

fix: Fixed 2D physics Shape naming duplication issue.

---

src/layaAir/laya/Light2D/Light2DManager.ts
src/layaAir/laya/components/IScenceComponentManager.ts
src/layaAir/laya/display/Scene.ts
src/layaAir/laya/navigation/common/BaseNavigationManager.ts
src/layaAir/laya/physics/Collider2D/ColliderBase.ts
src/layaAir/laya/physics/Physics2DWorldManager.ts
src/layaAir/laya/physics/RigidBody.ts
src/layaAir/laya/physics/Shape/BoxShape2D.ts
src/layaAir/laya/physics/Shape/ChainShape2D.ts
src/layaAir/laya/physics/Shape/CircleShape2D.ts
src/layaAir/laya/physics/Shape/EdgeShape2D.ts
src/layaAir/laya/physics/Shape/Physics2DShapeBase.ts
src/layaAir/laya/physics/Shape/PolygonShape2D.ts
src/layaAir/laya/physics/StaticCollider.ts
src/layaAir/laya/physics/factory/IPhysics2DFactory.ts
src/layaAir/laya/physics/factory/physics2DwasmFactory.ts
src/layaAir/laya/physics/joint/DistanceJoint.ts
src/layaAir/laya/physics/joint/GearJoint.ts
src/layaAir/laya/physics/joint/JointBase.ts
src/layaAir/laya/physics/joint/MotorJoint.ts
src/layaAir/laya/physics/joint/MouseJoint.ts
src/layaAir/laya/physics/joint/PrismaticJoint.ts
src/layaAir/laya/physics/joint/PulleyJoint.ts
src/layaAir/laya/physics/joint/RevoluteJoint.ts
src/layaAir/laya/physics/joint/WeldJoint.ts
src/layaAir/laya/physics/joint/WheelJoint.ts
src/samples/2d/Physics_CollisionFiltering_Shapes.ts

修复: 补充2D物理注释，修复QueryAABB与RayCast方法

fix: Add 2D physics comments and fix QueryAABB and RayCast methods.

---

src/layaAir/laya/NodeRender2D/BaseRenderNode2D.ts
src/layaAir/laya/RenderDriver/DriverDesign/RenderDevice/ShaderData.ts
src/layaAir/laya/display/Scene2DSpecial/RenderCMD2D/DrawMesh2DCMD.ts
src/layaAir/laya/tilemap/terrain/TileMapTerrain.ts
src/layaAir/laya/tilemap/terrain/TileMapTerrainUtils.ts

1. Fix issue with DrawMesh2DCMD.setColor not working.(DrawMesh2DCMD.setColor 无效的问题)
2. Add compatibility for spine's ColorFilter.(兼容spine的ColorFilter)
3. Fix Tile Terrain algorithm issue.(Tile的Terrain算法问题)

Fixed some bugs

---

src/layaAir/laya/Line2D/Draw2DLineCMD.ts
src/layaAir/laya/physics/Physics2DDebugDraw.ts
src/layaAir/laya/physics/Physics2DWorldManager.ts
src/layaAir/laya/physics/RigidBody.ts
src/layaAir/laya/physics/Shape/Physics2DShapeBase.ts
src/layaAir/laya/physics/StaticCollider.ts
src/layaAir/laya/physics/factory/physics2DwasmFactory.ts

fix: Fixed physics shape destruction issue.

---

scripts/config.mjs

fix: Fix particle dependency library issue, separate common library.

---

scripts/config.mjs

fix: Fixed 2D particle system compilation and export issues.

---

src/layaAir/laya/display/Scene2DSpecial/Camera2D.ts

fix:Solve the issue of two positions infinitely approaching each other

---

src/layaAir/laya/Physics3D/Bullet/Collider/btRigidBodyCollider.ts
src/layaAir/laya/Physics3D/Bullet/Shape/btColliderShape.ts
src/layaAir/laya/Physics3D/Bullet/Shape/btCompoundColliderShape.ts
src/layaAir/laya/Physics3D/Bullet/btPhysicsCreateUtil.ts
src/layaAir/laya/Physics3D/Bullet/btPhysicsManager.ts
src/layaAir/laya/Physics3D/PhysX/Collider/pxCollider.ts
src/layaAir/laya/Physics3D/PhysX/Shape/pxColliderShape.ts
src/layaAir/laya/Physics3D/PhysX/Shape/pxCompoundShape.ts
src/layaAir/laya/Physics3D/PhysX/pxPhysicsCreateUtil.ts
src/layaAir/laya/Physics3D/interface/IPhysicsCreateUtil.ts
src/layaAir/laya/Physics3D/interface/Shape/IColliderShape.ts
src/layaAir/laya/Physics3D/interface/Shape/ICompoundColliderShape.ts
src/layaAir/laya/d3/physics/PhysicsColliderComponent.ts
src/layaAir/laya/d3/physics/shape/CompoundColliderShape.ts
src/layaAir/laya/d3/physics/shape/Physics3DColliderShape.ts
src/layaAir/laya/renders/Context.ts
src/samples/3d/LayaAir3D_Physics3D/PhysicsWorld_CompoundCollider.ts

feat: Added the function of combining collision shapes.

---

src/layaAir/laya/navigation/Component/NavMeshModifierVolume.ts

fix: Fixed the issue with navigation mesh dynamic obstacles not working.

---

src/gulpfile.js
src/layaAir/jsLibs/laya.Alipaymini.js
src/layaAir/jsLibs/laya.bdmini.js
src/layaAir/jsLibs/laya.bilimini.js
src/layaAir/jsLibs/laya.hwmini.js
src/layaAir/jsLibs/laya.physics3D.wasm-alipay.js
src/layaAir/jsLibs/laya.qqmini.js
src/layaAir/jsLibs/laya.quickgamemini.js
src/layaAir/jsLibs/laya.tbappmini.js
src/layaAir/jsLibs/laya.tbmini.js
src/layaAir/jsLibs/laya.tbpluginmini.js
src/layaAir/jsLibs/laya.ttmini.js
src/layaAir/jsLibs/laya.vvmini.js
src/layaAir/jsLibs/laya.wxmini.js
src/layaAir/jsLibs/laya.xmmini.js

feat: Added Alipay wasm physical library adaptation.
